x-env_file: &env_file
  env_file:
    - .env

services:
  magento:
    image: ghcr.io/sequra/magento2-core:$M2_VERSION-$PHP_VERSION
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - $M2_HTTP_PORT:80
    volumes:
      - m2_html:/var/www/html
      - .:/Sequra/Core:ro
      - ./.docker/magento/HelperModule/Sequra:/var/www/html/app/code/Sequra
    extra_hosts:
      - "${M2_HTTP_HOST}:host-gateway"
    <<: *env_file

  mariadb:
    image: mariadb:$MARIADB_TAG
    ports:
      - $MARIADB_PORT:3306
    <<: *env_file
    volumes:
      - m2_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 10

  redis:
    image: redis:$REDIS_TAG
    ports:
      - $REDIS_PORT:6379
    volumes:
      - m2_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  elasticsearch:
    image: elasticsearch:$ELASTICSEARCH_TAG
    ports:
      - $ELASTICSEARCH_API_PORT:9200
      - $ELASTICSEARCH_INTERNODE_PORT:9300
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$ELASTICSEARCH_API_PORT"]
      interval: 3s
      timeout: 3s
      retries: 15
    volumes:
      - m2_elasticsearch:/usr/share/elasticsearch/data
  
volumes:
  m2_db:
  m2_redis:
  m2_elasticsearch:
  m2_html: